# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.hostname = "ollama"

  config.vm.box = "generic/ubuntu2004"
  config.vm.box_check_update = false
  config.vm.box_version = "4.3.2"
  
  # config.vm.network "public_network"#, ip: "192.168.1.42"
  config.vm.network "private_network"

  # config.vm.synced_folder "models", "/vagrant", mount_options: ["ro"]
  
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "1024"
    vb.cpus = "1"
  end

  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get curl -y
  #   curl -fsSL https://ollama.com/install.sh | sh
  # SHELL
end
